CREATE TABLE imagenes_yates (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    yate_id BIGINT UNSIGNED NOT NULL,
    imagen VARCHAR(255) NOT NULL,
    es_principal BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (yate_id) REFERENCES yates(id) ON DELETE CASCADE
);